---
name: Laravel

on:
  push:
    branches: [ "5.0" ]
  pull_request:
    branches: [ "5.0" ]

jobs:
  laravel-preview:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Install App
        run: composer run install-app
...
